blog/urls.py
from django.urls import path
from . import views, feeds

app_name = 'blog'

urlpatterns = [
    path('', views.PublicPostIndexView.as_view(), name='top'),
    path('private/', views.PrivatePostIndexView.as_view(), name='private_post_list'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('reply/create/<int:pk>/', views.ReplyCreate.as_view(), name='reply_create'),

    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/thanks/', views.subscribe_thanks, name='subscribe_thanks'),
    path('subscribe/register/<str:token>/', views.subscribe_register, name='subscribe_register'),
    path('subscribe/done/', views.subscribe_done, name='subscribe_done'),

    path('api/posts/suggest/', views.api_posts_suggest, name='api_posts_suggest'),
    path('api/image/upload/', views.api_image_upload, name='api_image_upload'),

    path('rss/', feeds.RssLatestPostsFeed(), name='rss'),
    path('atom/', feeds.AtomLatestPostsFeed(), name='atom'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap, BlogSitemap
from portfolio.sitemaps import PortfolioSitemap
from diaries.sitemaps import DiarySitemap

sitemaps = {
    'posts': PostSitemap,
    'blog': BlogSitemap,
    'portfolio': PortfolioSitemap,
    'diary': DiarySitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('blog/', include('blog.urls')),
    path('diaries/', include('diaries.urls')),
    path('', include('portfolio.urls')),
]

# 開発環境でのメディアファイルの配信設定
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

blog/models.py
from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.shortcuts import resolve_url
from django.template.loader import render_to_string


class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255, unique=True)

    def __str__(self):
        if hasattr(self, 'post_count'):
            return f'{self.name}({self.post_count})'
        else:
            return self.name


class Post(models.Model):
    """記事"""
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    tags = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)

    relation_posts = models.ManyToManyField('self', verbose_name='関連記事', blank=True)
    is_public = models.BooleanField('公開可能か?', default=True)
    description = models.TextField('記事の説明', max_length=130)
    keywords = models.CharField('記事のキーワード', max_length=255, default='記事のキーワード')
    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title

    def line_push(self, request):
        """記事をラインで通知"""
        if settings.USE_LINE_BOT:
            import linebot
            from linebot.models import TextSendMessage
            context = {
                'post': self,
            }
            message = render_to_string('blog/mail/send_latest_notify_message.txt', context, request)
            line_bot_api = linebot.LineBotApi(settings.LINE_BOT_API_KEY)
            for push in LinePush.objects.all():
                line_bot_api.push_message(push.user_id, messages=TextSendMessage(text=message))

    def email_push(self, request):
        """記事をメールで通知"""
        context = {
            'post': self,
        }
        subject = render_to_string('blog/mail/send_latest_notify_subject.txt', context, request)
        message = render_to_string('blog/mail/send_latest_notify_message.txt', context, request)

        from_email = settings.DEFAULT_FROM_EMAIL
        bcc = [settings.DEFAULT_FROM_EMAIL]
        for mail_push in EmailPush.objects.filter(is_active=True):
            bcc.append(mail_push.email)
        email = EmailMessage(subject, message, from_email, [], bcc)
        email.send()

    def browser_push(self):
        """記事をブラウザ通知"""
        if settings.USE_WEB_PUSH:
            import requests
            data = {
                'app_id': settings.ONE_SIGNAL_APP_ID,
                'included_segments': ['All'],
                'contents': {'en': self.title},
                'headings': {'en': 'Naritoブログ'},
                'url': resolve_url('blog:post_detail', pk=self.pk),
            }
            requests.post(
                "https://onesignal.com/api/v1/notifications",
                headers={'Authorization': settings.ONE_SIGNAL_REST_KEY},
                json=data,
            )


class Comment(models.Model):
    """記事に紐づくコメント"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    email = models.EmailField('メールアドレス', blank=True, help_text='入力しておくと、返信があった際に通知します。コメント欄には表示されません。')
    target = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='対象記事')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:20]


class Reply(models.Model):
    """コメントに紐づく返信"""
    name = models.CharField('名前', max_length=255, default='名無し')
    text = models.TextField('本文')
    target = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='対象コメント')
    created_at = models.DateTimeField('作成日', auto_now_add=True)

    def __str__(self):
        return self.text[:20]


class LinePush(models.Model):
    """Lineでのプッシュ先を表す"""
    user_id = models.CharField('ユーザーID', max_length=100, unique=True)

    def __str__(self):
        return self.user_id


class EmailPush(models.Model):
    """メールでのプッシュ先を表す"""
    email = models.EmailField('メールアドレス', unique=True)
    is_active = models.BooleanField('有効フラグ', default=False)

    def __str__(self):
        return self.email

blog/forms.py
from django import forms
from django.db import models
from django.core.files.storage import default_storage
from django.urls import reverse_lazy
from .fields import SimpleCaptchaField
from .models import Comment, Reply, Tag, Post, EmailPush
from .widgets import SuggestPostWidget, SimpleMDE, AdminSimpleMDE


TITLE_CONTAIN = '1'
TEXT_CONTAIN = '2'
TITLE_OR_TEXT_CONTAIN = '3'
COMMENT_CONTAIN = '4'

AND = '1'
OR = '2'


class PostSearchForm(forms.Form):
    """記事検索フォーム。"""
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
    )

    search_kind = forms.ChoiceField(
        label='キーワード検索タイプ',
        required=False,
        choices=[
            (TITLE_OR_TEXT_CONTAIN, 'タイトルか本文に含む'), (TITLE_CONTAIN, 'タイトルに含む'),
            (TEXT_CONTAIN, '本文に含む'), (COMMENT_CONTAIN, 'コメントに含む'),
        ],
    )

    search_tags = forms.ModelMultipleChoiceField(
        label='タグでの絞り込み',
        required=False,
        queryset=Tag.objects.annotate(post_count=models.Count('post')).order_by('name'),
    )

    search_tags_kind = forms.ChoiceField(
        label='タグの検索タイプ',
        required=False,
        choices=[(AND, 'AND'), (OR, 'OR')],
    )

    page_nums = forms.IntegerField(
        label='1ページの表示件数',
        required=False,
        min_value=1,
    )


class AdminPostCreateForm(forms.ModelForm):
    """記事の作成・更新フォーム"""

    class Meta:
        model = Post
        fields = ['title', 'is_public', 'description', 'keywords', 'text', 'relation_posts', 'tags']
        widgets = {
            'text': AdminSimpleMDE,
            'relation_posts': SuggestPostWidget(attrs={'data-url': reverse_lazy('blog:api_posts_suggest')}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.annotate(
            post_count=models.Count('post')
        ).order_by('name')


class CommentCreateForm(forms.ModelForm):
    """コメント投稿フォーム"""
    captcha = SimpleCaptchaField()

    class Meta:
        model = Comment
        fields = ('name', 'text', 'email')
        widgets = {
            'text': SimpleMDE,
        }


class ReplyCreateForm(forms.ModelForm):
    """返信コメント投稿フォーム"""
    captcha = SimpleCaptchaField()

    class Meta:
        model = Reply
        fields = ('name', 'text')
        widgets = {
            'text': SimpleMDE,
        }


class EmailForm(forms.ModelForm):
    """Eメール通知の登録用フォーム"""

    class Meta:
        model = EmailPush
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data['email']
        EmailPush.objects.filter(email=email, is_active=False).delete()
        return email


class FileUploadForm(forms.Form):
    """ファイルのアップロードフォーム"""
    file = forms.FileField()

    def save(self):
        upload_file = self.cleaned_data['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        file_url = default_storage.url(file_name)
        return file_url

blog/views.py
import json
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.db.models import Q, Count
from django.http import Http404, JsonResponse, HttpResponseBadRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from .forms import (
    PostSearchForm, CommentCreateForm, ReplyCreateForm,
    TITLE_CONTAIN, TEXT_CONTAIN, TITLE_OR_TEXT_CONTAIN, EmailForm, AND,
    FileUploadForm, COMMENT_CONTAIN
)
from .models import Post, Tag, Comment, Reply, EmailPush, LinePush


class PublicPostIndexView(generic.ListView):
    """公開記事の一覧を表示する。"""
    paginate_by = 10
    model = Post

    def get_queryset(self):
        queryset = super().get_queryset()
        self.request.form = form = PostSearchForm(self.request.GET)
        form.is_valid()

        tags = form.cleaned_data.get('search_tags')
        search_kind = form.cleaned_data.get('search_kind')
        key_word = form.cleaned_data.get('key_word')
        page_nums = form.cleaned_data.get('page_nums')
        search_tags_kind = form.cleaned_data.get('search_tags_kind')

        # タグを選択していれば、それで絞り込む
        if tags:
            if search_tags_kind == AND:
                for tag in tags:
                    queryset = queryset.filter(tags=tag)
            else:
                queryset = queryset.filter(tags__in=tags)

        # キーワードが入力されていれば、いずれかの方法で絞り込む
        # キーワードが半角スペースで区切られていれば、その回数だけfilterします。つまりANDです。
        if key_word:
            # タイトルに含む
            if search_kind == TITLE_CONTAIN:
                for word in key_word.split():
                    queryset = queryset.filter(title__icontains=word)

            # 本文に含む
            elif search_kind == TEXT_CONTAIN:
                for word in key_word.split():
                    queryset = queryset.filter(text__icontains=word)

            # タイトルか本文に含む
            elif search_kind == TITLE_OR_TEXT_CONTAIN:
                for word in key_word.split():
                    queryset = queryset.filter(Q(title__icontains=word) | Q(text__icontains=word))

            # コメントに含む
            elif search_kind == COMMENT_CONTAIN:
                comment_list = Comment.objects.all()
                for word in key_word.split():
                    comment_list = comment_list.filter(Q(text__icontains=word) | Q(name__icontains=word))

                reply_list = Reply.objects.all()
                for word in key_word.split():
                    reply_list = reply_list.filter(Q(text__icontains=word) | Q(name__icontains=word))

                post_ids = {comment.target.pk for comment in comment_list} | {reply.target.target.pk for reply in reply_list}
                queryset = queryset.filter(id__in=post_ids)

        # 表示件数の指定があれば
        if page_nums:
            self.paginate_by = page_nums

        queryset = queryset.filter(
            is_public=True
        ).order_by('-created_at').prefetch_related('tags')
        return queryset


class PrivatePostIndexView(LoginRequiredMixin, generic.ListView):
    """非公開の記事一覧を表示する。"""
    model = Post

    def get_queryset(self):
        queryset = Post.objects.filter(
            is_public=False
        ).order_by('-created_at').prefetch_related('tags')
        return queryset


class PostDetailView(generic.DetailView):
    """記事詳細ページを表示する。"""
    model = Post

    def get_queryset(self):
        return super().get_queryset().prefetch_related('tags', 'comment_set__reply_set')

    def get_object(self, queryset=None):
        """その記事が公開か、ユーザがログインしていれば表示する。"""
        post = super().get_object()
        if post.is_public or self.request.user.is_authenticated:
            return post
        else:
            raise Http404


class CommentCreate(generic.CreateView):
    """記事へのコメント作成ビュー。"""
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.request = self.request
        comment.save()
        messages.info(self.request, 'コメントしました。')
        return redirect('blog:post_detail', pk=post_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context


class ReplyCreate(generic.CreateView):
    """コメントへの返信作成ビュー。"""
    model = Reply
    form_class = ReplyCreateForm
    template_name = 'blog/comment_form.html'

    def form_valid(self, form):
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(Comment, pk=comment_pk)
        reply = form.save(commit=False)
        reply.target = comment
        reply.request = self.request
        reply.save()
        messages.info(self.request, '返信しました。')
        return redirect('blog:post_detail', pk=comment.target.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_pk = self.kwargs['pk']
        comment = get_object_or_404(Comment, pk=comment_pk)
        context['post'] = comment.target
        return context


def subscribe(request):
    """ブログの購読ページ"""
    form = EmailForm(request.POST or None)
    # メール購読の処理
    if request.method == 'POST' and form.is_valid():
        push = form.save()
        context = {
            'token': dumps(push.pk),
        }
        subject = render_to_string('blog/mail/confirm_push_subject.txt', context, request)
        message = render_to_string('blog/mail/confirm_push_message.txt', context, request)

        from_email = settings.DEFAULT_FROM_EMAIL
        to = [push.email]
        bcc = [settings.DEFAULT_FROM_EMAIL]
        email = EmailMessage(subject, message, from_email, to, bcc)
        email.send()

        return redirect('blog:subscribe_thanks')

    context = {
        'form': form,
        'USE_LINE_BOT': settings.USE_LINE_BOT,
        'USE_WEB_PUSH': settings.USE_WEB_PUSH,
    }
    if settings.USE_WEB_PUSH:
        context['ONE_SIGNAL_APP_ID'] = settings.ONE_SIGNAL_APP_ID

    return render(request, 'blog/subscribe.html', context)


def subscribe_thanks(request):
    """メール購読ありがとう、確認メール送ったよページ"""
    return render(request, 'blog/subscribe_thanks.html')


def subscribe_register(request, token):
    """メール購読の確認処理"""
    try:
        user_pk = loads(token, max_age=60*60*24)  # 1日以内

    # 期限切れ
    except SignatureExpired:
        return HttpResponseBadRequest()

    # tokenが間違っている
    except BadSignature:
        return HttpResponseBadRequest()

    # tokenは問題なし
    else:
        try:
            push = EmailPush.objects.get(pk=user_pk)
        except EmailPush.DoesNotExist:
            return HttpResponseBadRequest()
        else:
            if not push.is_active:
                # まだ仮登録で、他に問題なければ本登録とする
                push.is_active = True
                push.save()
                return redirect('blog:subscribe_done')

    return HttpResponseBadRequest()


def subscribe_done(request):
    """メール購読完了"""
    return render(request, 'blog/subscribe_done.html')


@csrf_exempt
def line_callback(request):
    """ラインの友達追加時に呼び出され、ラインのIDを登録する。"""
    if request.method == 'POST':
        request_json = json.loads(request.body.decode('utf-8'))
        line_user_id = request_json['events'][0]['source']['userId']
        LinePush.objects.create(user_id=line_user_id)
    return HttpResponse()


def api_image_upload(request):
    """ファイルのアップロード用ビュー"""
    form = FileUploadForm(files=request.FILES)
    if form.is_valid():
        url = form.save()
        return JsonResponse({'url': url})
    return HttpResponseBadRequest()


def api_posts_suggest(request):
    """サジェスト候補の記事をJSONで返す。"""
    keyword = request.GET.get('keyword')
    if keyword:
        post_list = [{'pk': post.pk, 'name': str(post)} for post in Post.objects.filter(title__icontains=keyword)]
    else:
        post_list = []
    return JsonResponse({'object_list': post_list})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="{% block keywords %}Python,Django,プログラミング,ブログ{% endblock %}">
    <meta name="description" content="{% block description %}{% endblock %}">
    <title>{% block title %}UTMJN Blog{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic|Source+Code+Pro&display=swap" rel="stylesheet">

    {% block extrahead %}{% endblock %}
</head>
<body>
{% if messages %}
    <div id="notify">
        {% for message in messages %}
            <p> {{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

<header id="site-header">
    <h1>UTMJN Blog</h1>
    <nav id="site-nav">
        <ul>
            <li><a href="{% url 'blog:top' %}">一覧・検索</a></li>
            <li><a href="{% url 'blog:subscribe' %}">購読する</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'blog:private_post_list' %}">非公開</a></li>
                <li><a href="{% url 'admin:login' %}" target="_blank">admin</a></li>
            {% endif %}
        </ul>
    </nav>
</header>



<form action="{% url 'blog:top' %}" method="get" role="search" id="top-form">
    {{ search_form.key_word }}<button type="submit" id="search">検索</button><br>
    {% for field in search_form %}
        {% if field.name != 'key_word' %}
            <div class="dropdown-container">
                <p class="dropdown-trigger">{{ field.label }}</p>
                <div class="dropdown-item">
                    {{ field }}
                </div>
            </div>
        {% endif %}
    {% endfor %}
</form>

{% block content %}{% endblock %}

<footer id="site-footer">
    <ul>
        <li><a href="https://narito.ninja/">ポートフォリオ</a></li>
        <li><a href="https://github.com/naritotakizawa/narito.ninja/tree/master/blog/" target="_blank" rel="nofollow">このブログのソースコード</a>
        </li>
        <li><a href="http://www.amazon.co.jp/registry/wishlist/2ZCE9KHVM7FRA/ref=cm_sw_r_tw_ws_f.aTzbDCX47K6"
               target="_blank" rel="nofollow">欲しいもの</a></li>
        <li>
            <a href="https://www.amazon.co.jp/gp/profile/amzn1.account.AGTGNAWPJUIZH5QTUTN4USFNSO5Q/ref=cm_cr_dp_d_gw_tr?ie=UTF8"
               target="_blank" rel="nofollow">書籍レビュー</a></li>
        <li><a href="https://torina.top/" target="_blank" rel="nofollow">旧ブログ</a></li>
        <li><a href="mailto:toritoritorina@gmail.com">メール</a></li>
        <li>© GEN TOMITA</li>
    </ul>
</footer>

<script>
    // トップにある検索フォームの、各ドロップダウン展開イベント
    document.addEventListener('DOMContentLoaded', () => {
        for (const element of document.getElementsByClassName('dropdown-trigger')) {
            element.addEventListener('click', e => {
               element.nextElementSibling.classList.toggle('show');
            });
        }
    });
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-72333380-3"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-72333380-3');
</script>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
    <form action="" method="POST" id="comment-form">
        {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <span class="helptext">{{ field.help_text }}</span>
                {% endif %}
                {{ field.errors }}
            </div>
        {% endfor %}
        {% csrf_token %}

        <button type="submit">送信</button>
        <a class="button" href="{% url 'blog:post_detail' post.pk %}">送信せずに戻る</a>
    </form>

{% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'blog/css/comment_form.css' %}">
    {{ form.media }}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load blog %}
{% load static %}
{% block title %}{{ post.title }} - Narito Blog{% endblock %}
{% block description %}{{ post.description }}{% endblock %}
{% block keywords %}{{ post.keywords }}{% endblock %}

{% block content %}
    <div class="post-head">
        <h1>
            {% if user.is_authenticated %}
                <a href="{% url 'admin:blog_post_change' post.pk %}" target="_blank">{{ post.title }}</a>
            {% else %}
                {{ post.title }}
            {% endif %}
        </h1>
        <p class="meta">
            <span class="created_at">{{ post.created_at | date:'Y-m-d' }}</span>
            /
            {% for tag in post.tags.all %}<span class="tag">{{ tag }}</span>{% endfor %}
        </p>
        <p class="description">
            <time class="updated_at" datetime="{{ post.updated_at | date:'Y-m-d' }}">{% by_the_time post.updated_at %}に更新</time>
        </p>
    </div>

    <aside id="ads">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-5235456993770661"
             data-ad-slot="2942976583"
             data-ad-format="auto"
             data-full-width-responsive="true"></ins>
        <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </aside>

    <section class="markdown-body">
        {{ post.text | markdown_to_html }}
    </section>

    <section id="relation-posts">
        <h2>この記事の関連記事</h2>
        {% for post in post.relation_posts.all %}
            <article class="post">
                <h2><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h2>
                <p class="meta">
                    <span class="created_at">{{ post.created_at | date:'Y-m-d' }}</span>
                    /
                    {% for tag in post.tags.all %}<span class="tag">{{ tag }}</span>{% endfor %}
                </p>
                <p class="description">
                    <time class="updated_at" datetime="{{ post.updated_at | date:'Y-m-d' }}">{% by_the_time post.updated_at %}に更新</time>
                    -
                    {{ post.description }}
                </p>
            </article>
        {% empty %}
            <p>関連記事はありません。</p>
        {% endfor %}
    </section>

    <section id="comment">
        <h2>コメント欄</h2>
        <!-- コメント一覧 -->
        <p><a href="{% url 'blog:comment_create' post.pk %}" target="_blank" rel="nofollow">記事にコメントする</a>
            {% for comment in post.comment_set.all %}
                <div class="card markdown-body">
                    {{ comment.name }}
                    <time datetime="{{ comment.created_at | date:'Y-m-d' }}">{% by_the_time comment.created_at %}</time>

                    {{ comment.text | markdown_to_html_with_escape }}

                <p>
                    <a href="{% url 'blog:reply_create' comment.pk %}" target="_blank"
                       rel="nofollow">コメントに返信する</a>
                </p>

                <!-- リプライ一覧 -->
                {% for reply in comment.reply_set.all %}
                    <div class="card markdown-body">
                        {{ reply.name }}
                        <time datetime="{{ reply.created_at | date:'Y-m-d' }}">{% by_the_time reply.created_at %}</time>
                        <div class="markdown-body">
                            {{ reply.text | markdown_to_html_with_escape }}
                        </div>
                    </div>
                {% endfor %}
                <!-- リプライ一覧終わり -->

                </div>


            {% empty %}
                <p>まだコメントはありません。</p>

            {% endfor %}
        <!-- コメント一覧終わり -->
    </section>

    <nav id="post-nav" class="toc"></nav>

{% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'blog/css/post_detail.css' %}">
    <!-- コードシンタックス、css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/dracula.min.css">
    <!-- コードシンタックス、js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
    <script>
        // ハイライト
        hljs.initHighlightingOnLoad();

        // 画像の読み込みを待つ必要があるので、loadイベント
        window.onload = e => {

            // 記事内目次( [TOC]で生成される )
            const toc = document.querySelector('section.markdown-body div.toc');

            // [TOC]があれば
            if (toc) {

                // 記事内目次をコピー
                const copyTocUl = toc.getElementsByTagName('ul')[0].cloneNode(true);

                // サイドナビに目次を挿入
                const nav = document.getElementById('post-nav');
                nav.insertBefore(copyTocUl, nav.firstChild);

                // [[#summary, a要素], [#about-python, a要素]]のような配列。
                const anchors = [];
                for (const a of nav.getElementsByTagName('a')) {
                    const id = new URL(a.href).hash;
                    anchors.push([id, a]);
                }

                // [[summary, 100]. [about-python, 200]]のような、id名, yの絶対座標な配列
                const headings = [];
                for (const element of document.querySelectorAll('section.markdown-body > h2, section.markdown-body > h3')) {
                    const rect = element.getBoundingClientRect();
                    headings.push([element.id, window.pageYOffset + rect.top]);
                }

                // 配列を逆にしておく。
                headings.reverse();

                window.addEventListener('scroll', e => {

                    // 現在のスクロール位置的に、どのh2 or h3の部分か調べる。
                    let currentHeadingsId = null;
                    for (const [id, top] of headings) {
                        if (window.pageYOffset >= top - 10) {  // なんか、誤差があるので10pxぐらい足しとく。いつか調べる
                            currentHeadingsId = id;
                            break;
                        }
                    }

                    // 今のh2, h3に対応する目次のリンクの色を変える。
                    if (currentHeadingsId) {
                        for (const [id, a] of anchors) {
                            if (id === `#${currentHeadingsId}`) {
                                a.classList.add('current');
                            } else {
                                a.classList.remove('current');
                            }
                        }

                    }
                });
            }
        };

    </script>
{% endblock %}