blog/urls.py
from django.urls import path
from . import views, feeds

app_name = 'blog'

urlpatterns = [
    path('', views.PublicPostIndexView.as_view(), name='top'),
    path('private/', views.PrivatePostIndexView.as_view(), name='private_post_list'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('comment/create/<int:pk>/', views.CommentCreate.as_view(), name='comment_create'),
    path('reply/create/<int:pk>/', views.ReplyCreate.as_view(), name='reply_create'),

    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/thanks/', views.subscribe_thanks, name='subscribe_thanks'),
    path('subscribe/register/<str:token>/', views.subscribe_register, name='subscribe_register'),
    path('subscribe/done/', views.subscribe_done, name='subscribe_done'),

    path('api/posts/suggest/', views.api_posts_suggest, name='api_posts_suggest'),
    path('api/image/upload/', views.api_image_upload, name='api_image_upload'),

    path('rss/', feeds.RssLatestPostsFeed(), name='rss'),
    path('atom/', feeds.AtomLatestPostsFeed(), name='atom'),
]

diaries/urls.py
from django.urls import path
from . import views, feeds

app_name = 'diaries'

urlpatterns = [
    path('', views.DiaryList.as_view(), name='list'),
    path('search/', views.DiarySearchList.as_view(), name='search'),
    path('archive/<int:year>/', views.DiaryYearList.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/', views.DiaryMonthList.as_view(), name='month'),
    path('category/<int:pk>/', views.DiaryCategoryList.as_view(), name='category'),
    path('detail/<int:pk>/', views.DiaryDetail.as_view(), name='detail'),
    path('rss/', feeds.LatestDiaryFeed(), name='rss'),
    path('upload/', views.upload, name='upload'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap, BlogSitemap
from portfolio.sitemaps import PortfolioSitemap
from diaries.sitemaps import DiarySitemap

sitemaps = {
    'posts': PostSitemap,
    'blog': BlogSitemap,
    'portfolio': PortfolioSitemap,
    'diary': DiarySitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
    path('blog/', include('blog.urls')),
    path('diaries/', include('diaries.urls')),
    path('', include('portfolio.urls')),
]

# 開発環境でのメディアファイルの配信設定
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

diaries/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """日記のカテゴリ"""
    name = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.name


class DiaryQuerySet(models.QuerySet):

    def published(self):
        return self.filter(created_at__lte=timezone.now())


class Diary(models.Model):
    """日記"""
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    objects = DiaryQuerySet.as_manager()

    def __str__(self):
        return self.title

diaries/forms.py
from django import forms
from django.core.files.storage import default_storage


class DiarySearchForm(forms.Form):
    """検索フォーム。"""
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
    )


class FileUploadForm(forms.Form):
    """ファイルのアップロードフォーム"""
    file = forms.FileField()

    def save(self):
        upload_file = self.cleaned_data['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        file_url = default_storage.url(file_name)
        return file_url

diaries/views.py
from django.db.models import Q
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import generic
from .forms import DiarySearchForm, FileUploadForm
from .models import Diary, Category


class DiaryMixin:
    model = Diary
    paginate_by = 10
    date_field = 'created_at'
    template_name = 'diaries/diary_list.html'
    allow_empty = True
    make_object_list = True


class DiaryList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '最近の日記'
        return context


class DiarySearchList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        queryset = super().get_queryset()
        self.request.form = form = DiarySearchForm(self.request.GET)
        form.is_valid()
        self.key_word = key_word = form.cleaned_data['key_word']
        if key_word:
            queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 の検索結果'.format(self.key_word)
        return context


class DiaryCategoryList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        self.category = category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 カテゴリの日記'.format(self.category.name)
        return context


class DiaryYearList(DiaryMixin, generic.YearArchiveView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年の日記'.format(self.kwargs['year'])
        return context


class DiaryMonthList(DiaryMixin, generic.MonthArchiveView):
    month_format = '%m'

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年{}月の日記'.format(self.kwargs['year'], self.kwargs['month'])
        return context


class DiaryDetail(generic.DetailView):
    model = Diary

    def get_object(self, queryset=None):
        diary = super().get_object()
        if diary.created_at <= timezone.now():
            return diary
        raise Http404


def upload(request):
    """ファイルのアップロード用ビュー"""
    form = FileUploadForm(files=request.FILES)
    if form.is_valid():
        path = form.save()
        url = '{0}://{1}{2}'.format(
            request.scheme,
            request.get_host(),
            path,
        )
        return JsonResponse({'url': url})
    return HttpResponseBadRequest()

diaries/templates/diaries/base.html
{% load static %}
{% load diary %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description"
          content="{% block description %}なりとの日記帳です。とりとめない呟きや、感想、思ったことを書いています。毒にも薬にもならないでしょう。{% endblock %}">
    <link rel="stylesheet" href="{% static 'diaries/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond:400i|Noto+Serif+JP:300,500&display=swap"
          rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
</head>
<body>

<header>
    <p id="title"><a href="{% url 'diaries:list' %}">My Diary</a></p>
    <p id="subtitle">Copyright 2019 Gen Tomita.</p>
</header>

<nav id="menu">
    <button class="menu-trigger" data-target="sub">Menu</button>
</nav>

<main>
    {% block content %}{% endblock %}
</main>


<aside id="ads">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-5235456993770661"
         data-ad-slot="2942976583"
         data-ad-format="auto"
         data-full-width-responsive="true"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</aside>

<aside id="sub">
    <button class="menu-trigger" data-target="sub">Close</button>

    <h2>Archives</h2>
    {% render_month_links %}

    <h2>Category</h2>
    {% render_category_links %}

    <h2>Link</h2>
    <ul>
        <li><a href="..">HOME</a></li>
        <li><a href="mailto:toritoritorina@gmail.com">Email</a></li>
        <li><a href="https://twitter.com/GenTomitaCa">Twitter Account</a></li>
        <li><a href="https://github.com/NMZ0429">Github Account</a></li>
        <li><a href="https://www.youtube.com/channel/UCKkxv5imYVE_OzbklvWV7DQ?view_as=subscriber">Official YouTube Channel</a>
        </li>
        <li><a href="https://github.com/naritotakizawa/narito.ninja/tree/master/diaries/">デバック用</a></li>
    </ul>

    <h2>Search</h2>
    {% render_search_form request %}

    <h2>Feeds</h2>
    <ul>
        <li><a href="{% url 'diaries:rss' %}">Latest Diaries</a></li>
    </ul>

</aside>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
    AOS.init();

    // ナビバーの開閉を設定
    for (const trigger of document.getElementsByClassName('menu-trigger')) {
        const menuId = trigger.dataset.target;
        const menu = document.getElementById(menuId);
        trigger.addEventListener('click', e => {
            trigger.classList.toggle('active');
            menu.classList.toggle('active');
        });
    }
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-72333380-3"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-72333380-3');
</script>
</body>
</html>

diaries/templates/diaries/diary_detail.html
{% extends 'diaries/base.html' %}
{% load diary %}

{% block title %}{{ diary.title }} - My Diary{% endblock %}

{% block content %}
    <p id="back"><a href="#" onclick="window.history.back(); return false;">戻る</a></p>
    <article data-aos="fade-up" data-aos-duration="1000">
        <h1>{{ diary.title }}</h1>
        <div class="contents">
            {{ diary.text | linebreaks | urlize2 }}
        </div>
        <p class="meta">
            {{ diary.category }}
            <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
        </p>
    </article>
{% endblock %}

diaries/templates/diaries/diary_list.html
{% extends 'diaries/base.html' %}
{% load diary %}

{% block title %}{{ heading }} - My Diary{% endblock %}

{% block content %}

    <h1>{{ heading }}</h1>

    {% for diary in object_list %}

        <article data-aos="fade-up" data-aos-duration="1000">
            <h2>{{ diary.title }}</h2>
            <div class="contents">
                {{ diary.text | linebreaks | urlize2 | truncatechars_html:300 }}
                <p><a href="{% url 'diaries:detail' diary.pk %}">続きを読む</a></p>
            </div>
            <p class="meta">
                {{ diary.category }}
                <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
            </p>
        </article>

    {% empty %}
        <p>記事が見つかりませんでした。</p>
    {% endfor %}

    <nav id="page">

        <!-- 1つ前 の部分 -->
        {% if page_obj.has_previous %}
            <a id="prev" href="?{% url_replace request 'page' page_obj.previous_page_number %}"
               title="前ページへ">前ページ</a>
        {% endif %}

        <span id="page-info">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

        <!-- 1つ後 の部分 -->
        {% if page_obj.has_next %}
            <a id="next" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次ページ</a>
        {% endif %}
    </nav>

{% endblock %}